[package]
name = 'rosm4routing'
version = '0.1.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = { git = 'https://github.com/extendr/extendr' }
osmpbfreader = "0.15.2"
csv = "1.1.3"
osm4routing = "0.4.0"
