# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rosm4routing_wrappers", use_symbols = TRUE, package_name = "rosm4routing")

#' @docType package
#' @usage NULL
#' @useDynLib rosm4routing, .registration = TRUE
NULL

#' Convert OpenStreetMap OSM.PBF files into CSV files
#' @param filename A character string; the path to the OSM.PBF file.
main <- function(filename) invisible(.Call(wrap__main, filename))

